version: '3.8'

services:
  # 1. Base de Datos
  postgres:
    image: postgres:14.4-alpine
    container_name: billing_challenge_db
    ports:
      - "5434:5432" # Expuesto al host en 5434 por si quieres ver la DB localmente
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=billing_challenge
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - billing_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. Redis (Para las Colas)
  redis:
    image: redis:alpine
    container_name: billing_challenge_redis
    ports:
      - "6379:6379"
    networks:
      - billing_network

  # 3. La API (NestJS)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: billing_challenge_api
    ports:
      - "3000:3000"
    environment:
      # OJO: Aqu√≠ usamos los nombres de los servicios (postgres, redis) como hosts
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=billing_challenge
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=super_secret_key_change_me
      - JWT_EXPIRES_IN=24h
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - billing_network
    # Comando: Ejecuta migraciones y luego arranca
    command: sh -c "npm run typeorm:run && npm run start:dev"

volumes:
  postgres_data:
    driver: local

networks:
  billing_network:
    driver: bridge